/*
 * error.h
 *
 *  Created on: Apr 6, 2015
 *      Author: root
 */

#ifndef LIBTOBOR_IO2_INCLUDE_EM_ERROR_H_
#define LIBTOBOR_IO2_INCLUDE_EM_ERROR_H_

#define EM_SUCCESS 0


#define EM_ERROR_MEMORY_ALLOCATION 1
#define EM_ERROR_UNKNOWNMODEL 2
#define EM_ERROR_PIN_TYPE 3
#define EM_ERROR_IO 4
#define EM_ERROR_UNKNOWN_PARAMETER 5
#define EM_ERROR_CANNOT_OPEN 6
#define EM_ERROR_PIN_NUMBER_INVALID 7
#define EM_ERROR_IO_WRITE 8
#define EM_ERROR_IO_READ 9
#define EM_ERROR_NOT_IMPLEMENTED 10
#define EM_ERROR_IO_TIMEOUT 11

#endif /* LIBTOBOR_IO2_INCLUDE_EM_ERROR_H_ */
